FROM node:22

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV FIRECRAWL_API_KEY=dummy_key
ENV NEXT_PUBLIC_SUPABASE_URL=dummy_url
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy_key
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=dummy_key
ENV SUPABASE_SERVICE_ROLE_KEY=dummy_key
ENV CRON_SECRET=dummy_secret
ENV RESEND_API_KEY=dummy_key
ENV RESEND_FROM_EMAIL=test@test.com

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]